### ISSUE TITLE
Azure DevOps version 1.0.1 & 1.1.1 Provider crash

### ISSUE THREAD

**Issue by thegooddalton** [microsoft/terraform-provider-azuredevops#1060]
Please see Stack trace from terraform-provider-azuredevops

│   with azuredevops_serviceendpoint_kubernetes.this,
│   on main.tf line 28, in resource "azuredevops_serviceendpoint_kubernetes" "this":
│   28: resource "azuredevops_serviceendpoint_kubernetes" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-azuredevops_v1.0.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcb6e96]

goroutine 48 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.resourceServiceEndpointKubernetesRead(0x0?, {0xd61b20?, 0xc000379ce0})
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go:219 +0xb6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10966a0?, {0x10966a0?, 0xc000465980?}, 0xd?, {0xd61b20?, 0xc000379ce0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000393a40, {0x10966a0, 0xc000465980}, 0xc0003de820, {0xd61b20, 0xc000379ce0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002e0768, {0x10966a0?, 0xc000465860?}, 0xc0001b8cc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002a1180, {0x10966a0?, 0xc000464ff0?}, 0xc0005288a0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xedf280?, 0xc0002a1180}, {0x10966a0, 0xc000464ff0}, 0xc00038cc40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0x1099400, 0xc00035e000}, 0xc00051e5a0, 0xc0003d6a20, 0x16242d0, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0x1099400, 0xc00035e000}, 0xc00051e5a0, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-azuredevops_v1.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by thegooddalton** [comment]
This was caused by someone breaking the state, closing, although better panic output would be good!
