### ISSUE TITLE
Unexpectedly Terraform apply crash

### ISSUE THREAD

**Issue by Chathuru** [microsoft/terraform-provider-azuredevops#214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v0.13.4

### Affected Resource(s)
- Service Endpoints
- Build Definitions

### Terraform Configuration Files

```
provider "azuredevops" {
  org_service_url = "https://dev.azure.com/org/"
  personal_access_token ="xxxxx"
  version = ">= 0.0.1"
}
resource "azuredevops_serviceendpoint_github" "github" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "GitHubEndpoin"

  auth_personal {
    personal_access_token = "xxxxxxxxxx"
  }
}
resource "azuredevops_resource_authorization" "auth-GitHub" {
  project_id  = azuredevops_project.project.id
  resource_id = azuredevops_serviceendpoint_github.github.id
  authorized  = true
  depends_on  = [azuredevops_serviceendpoint_github.github]
}
data "azuredevops_project" "p" {
  project_name = azuredevops_project.project.project_name
  depends_on   = [azuredevops_project.project]
}
resource "azuredevops_serviceendpoint_kubernetes" "azuredevops_serviceendpoint_kubernetes" {
  project_id            = data.azuredevops_project.p.project_name
  service_endpoint_name = "name"
  apiserver_url         = "https://url.azure.com"
  authorization_type    = "AzureSubscription"

  azure_subscription {
    subscription_id   = "xxxx"
    subscription_name = "xxxx"
    tenant_id         = "xxxx"
    resourcegroup_id  = "xxxx"
    namespace         = "xxxxx"
    cluster_name      = "xxxx"
  }
}
resource "azuredevops_resource_authorization" "azuredevops_resource_authorization" {
  project_id  = azuredevops_project.project.id
  resource_id = azuredevops_serviceendpoint_kubernetes.iamCloudConnection.id
  authorized  = true
  depends_on  = [azuredevops_serviceendpoint_kubernetes.iamCloudConnection]
}
```

### Debug Output

```
azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection: Creating...

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe4e6a9]
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: goroutine 36 [running]:
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.doBaseFlattening(0xc000315880, 0xc0006c9380, 0xc000236ed0)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:88 +0x179
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.flattenServiceEndpointKubernetes(0xc000315880, 0xc0006c9380, 0xc000236ed0)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go:242 +0x5d
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointCreateFunc.func1(0xc000315880, 0xee91e0, 0xc0001de300, 0x2, 0x1b328a0)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:173 +0x19a
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0000d1c80, 0xc0004e7130, 0xc000265900, 0xee91e0, 0xc0001de300, 0xf90f01, 0xc00008b3a8, 0xc000269170)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000430980, 0xc00024f8e0, 0xc0004e7130, 0xc000265900, 0xc000218aa8, 0xc00000efc8, 0xf92fa0)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000eb50, 0x137d860, 0xc0003fe8a0, 0xc00087b1a0, 0xc00000eb50, 0xc0003fe8a0, 0xc0001e9a48)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10c2d20, 0xc00000eb50, 0x137d860, 0xc0003fe8a0, 0xc00087b140, 0x0, 0x137d860, 0xc0003fe8a0, 0xc000581200, 0x429)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b0000, 0x138ab80, 0xc0001a0600, 0xc0000f6b00, 0xc0000e60f0, 0x1af8200, 0x0, 0x0, 0x0)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000b0000, 0x138ab80, 0xc0001a0600, 0xc0000f6b00, 0x0)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000364e0, 0xc0000b0000, 0x138ab80, 0xc0001a0600, 0xc0000f6b00)
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:710 +0xa1
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-02T07:17:05.991Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020/11/02 07:17:05 [DEBUG] azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/02 07:17:05 [TRACE] EvalMaybeTainted: azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection encountered an error during creation, so it is now marked as tainted
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalWriteState
2020/11/02 07:17:05 [TRACE] EvalWriteState: removing state object for azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/11/02 07:17:05 [TRACE] EvalApplyProvisioners: azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection has no state, so skipping provisioners
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/02 07:17:05 [TRACE] EvalMaybeTainted: azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection encountered an error during creation, so it is now marked as tainted
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalWriteState
2020/11/02 07:17:05 [TRACE] EvalWriteState: removing state object for azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalIf
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalIf
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalWriteDiff
2020/11/02 07:17:05 [TRACE] eval: *terraform.EvalApplyPost
2020/11/02 07:17:05 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/11/02 07:17:05 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/11/02 07:17:05 [TRACE] [walkApply] Exiting eval tree: azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection
2020/11/02 07:17:05 [TRACE] vertex "azuredevops_serviceendpoint_kubernetes.kubernetes_service_connection": visit complete
2020/11/02 07:17:05 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/terraform-providers/azuredevops\"] (close)" errored, so skipping
2020/11/02 07:17:05 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/11/02 07:17:05 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/11/02 07:17:05 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2020/11/02 07:17:06 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 121
2020/11/02 07:17:06 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020-11-02T07:17:06.001Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/terraform-providers/azuredevops/0.0.1/linux_amd64/terraform-provider-azuredevops_v0.0.1_x4 pid=8280 error="exit status 2"
2020/11/02 07:17:06 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/11/02 07:17:06 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-11-02T07:17:06.004Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by xuzhang3** [comment]
@Chathuru  This is a know issue caused by empty service connection description and I cannot reproduce your error. Can you  add a simple description to `azuredevops_serviceendpoint_kubernetes` service connection and try again? This issue has been fix in the latest branch.

**Comment by Chathuru** [comment]
@xuzhang3 Yes, I haven’t used a description when creating services endpoint. I will try with the description.

**Comment by Chathuru** [comment]
@xuzhang3 Tried building the code from the latest branch and its working. Thanks for your support.
