### ISSUE TITLE
Error deploying variable group

### ISSUE THREAD

**Issue by amarkulis** [microsoft/terraform-provider-azuredevops#237]
Error:
```
data.azuredevops_project.foundation: Refreshing state... [id=51bdfb32-5e85-41fa-bad2-dceb69eadd5f]
azuredevops_variable_group.variablegroup: Refreshing state... [id=65]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-11-25T16:39:21.041Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb56dc]
2020-11-25T16:39:21.041Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 
2020-11-25T16:39:21.041Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: goroutine 12 [running]:
2020-11-25T16:39:21.041Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.flattenVariableGroup(0xc00022a5b0, 0xc00007f260, 0xc000612e50, 0xc000612e50, 0xc000120390)
2020-11-25T16:39:21.041Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/azuredevops/internal/service/taskagent/resource_variable_group.go:361 +0x2c
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.resourceVariableGroupRead(0xc00022a5b0, 0xf51160, 0xc0002c6500, 0xc00022a5b0, 0x0)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/azuredevops/internal/service/taskagent/resource_variable_group.go:192 +0x33f
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004e4120, 0xc0004bef00, 0xf51160, 0xc0002c6500, 0xc0001253d0, 0x0, 0x0)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x119
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000124d08, 0x1416d80, 0xc000088540, 0xc000127500, 0xc000124d08, 0xc000088540, 0xc00006ab78)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1147620, 0xc000124d08, 0x1416d80, 0xc000088540, 0xc000127380, 0x0, 0x1416d80, 0xc000088540, 0xc00024e400, 0x3c1)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001800, 0x1425940, 0xc000107380, 0xc000177300, 0xc0001a0060, 0x1badaf0, 0x0, 0x0, 0x0)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/google.golang.org/grpc/server.go:1024 +0x501
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: google.golang.org/grpc.(*Server).handleStream(0xc000001800, 0x1425940, 0xc000107380, 0xc000177300, 0x0)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000120470, 0xc000001800, 0x1425940, 0xc000107380, 0xc000177300)
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/google.golang.org/grpc/server.go:722 +0xa1
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-25T16:39:21.042Z [DEBUG] plugin.terraform-provider-azuredevops_v0.1.0: 	/home/vsts/work/1/s/vendor/google.golang.org/grpc/server.go:720 +0xa1
2020-11-25T16:39:21.044Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/microsoft/azuredevops/0.1.0/linux_amd64/terraform-provider-azuredevops_v0.1.0 pid=15603 error="exit status 2"
2020/11/25 16:39:21 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/11/25 16:39:21 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/11/25 16:39:21 [TRACE] [walkRefresh] Exiting eval tree: azuredevops_variable_group.variablegroup
2020/11/25 16:39:21 [TRACE] vertex "azuredevops_variable_group.variablegroup": visit complete
2020/11/25 16:39:21 [TRACE] vertex "azuredevops_variable_group.variablegroup": dynamic subgraph encountered errors
2020/11/25 16:39:21 [TRACE] vertex "azuredevops_variable_group.variablegroup": visit complete
2020/11/25 16:39:21 [TRACE] vertex "azuredevops_variable_group.variablegroup (expand)": dynamic subgraph encountered errors
2020/11/25 16:39:21 [TRACE] vertex "azuredevops_variable_group.variablegroup (expand)": visit complete
2020/11/25 16:39:21 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/microsoft/azuredevops\"] (close)" errored, so skipping
2020/11/25 16:39:21 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-11-25T16:39:21.064Z [DEBUG] plugin: plugin exited
```

Code:
```hcl
data "azuredevops_project" "foundation" {
  name = "PCET-AZR-NEW"
}

resource "azuredevops_variable_group" "variablegroup" {
  project_id   = data.azuredevops_project.foundation.id
  name         = "Test Variable Group"
  description  = "Test Variable Group Description"
  allow_access = true

    variable {
    name  = "key"
    value = "value"
  }

}
```

**Comment by xuzhang3** [comment]
@amarkulis  Can you share the steps when this error occurs? I tried  provider v0.0.1 and v0.1.0 and cannot reproduce your error.
Though the log,  it seems the variable group used in the TF script has been deleted.

**Comment by amarkulis** [comment]
@xuzhang3 I did delete the variable group. After deleting state file and starting over I was able to resolve the error. I didn't realize terraform would crash because of this.  Thank you.

**Comment by xuzhang3** [comment]
@amarkulis  It is not recommended to manage the resource both by Terraform and portal. Terraform cannot autodetect the resource changes, if you the resource changed out of Terraform, you need handle the changes carefully or Terraform may crash.   

 In your scenario, `terraform refresh` may help you.

**Comment by xuzhang3** [comment]
The issue will be closed, if you have any questions, please feel free to open it.
