### ISSUE TITLE
azuredevops_build_definition resource crashes terraform when path is empty string

### ISSUE THREAD

**Issue by rmaziarka** [microsoft/terraform-provider-azuredevops#272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
- terraform - v0.12.24
- azuredevops - v.0.0.1

### Affected Resource(s)

* `azuredevops_build_definition`

### Terraform Configuration Files

```hcl
resource "azuredevops_build_definition" "default" {
  project_id = azuredevops_project.default.id
  name       = "buildname"
  path       = ""

  repository {
    repo_type             = "TfsGit"
    repo_name             = "reponame"
    branch_name           = "master"
    yml_path              = "pipeline.yaml"
  }
}
```

### Panic Output

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: slice bounds out of range [:1] with length 0
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: goroutine 16 [running]:
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/microsoft/terraform-provider-azuredevops/azuredevops/utils/validate.Path(0xedda60, 0x1aa4840, 0x10bbe97, 0x4, 0x0, 0x0, 0x4fcb24, 0xf2e2c0, 0xc00017d960, 0x94)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/source/repos/terraform-provider-azuredevops/azuredevops/utils/validate/file_path.go:23 +0x5fd
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.validatePrimitive(0xc0004e41e0, 0x10bbe97, 0x4, 0xedda60, 0x1aa4840, 0xc00040f900, 0xc00017ec00, 0xc00017d940, 0xc00017d940, 0xedda60, ...)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/schema.go:1917 +0x30c
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.validateType(0xc0004e41e0, 0x10bbe97, 0x4, 0xedda60, 0x1aa4840, 0xc00040f900, 0xc00017ec00, 0x0, 0x0, 0x0, ...)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/schema.go:1936 +0x528
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.validate(0xc0004e41e0, 0x10bbe97, 0x4, 0xc00040f900, 0xc00017ec00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/schema.go:1434 +0x50d
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.validateObject(0xc0004e41e0, 0x0, 0x0, 0xc0004e41e0, 0xc00017ec00, 0x10d5aa4, 0xc00002ab40, 0x1c, 0x1, 0xd60000c00017cf60, ...)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/schema.go:1810 +0x1d6
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.Validate(...)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/schema.go:686
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Validate(0xc000194b80, 0xc00017ec00, 0xc00002ab40, 0x1c, 0xc0003d0708, 0x1, 0x1, 0xc00017ec00)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/resource.go:376 +0x64
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ValidateResource(0xc000195700, 0xc00002ab40, 0x1c, 0xc00017ec00, 0xc00017cf50, 0xc00017ec00, 0xc00008e038, 0xf50cc0, 0xc00017eba0, 0x0)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/provider.go:246 +0x18e
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ValidateResourceTypeConfig(0xc000188548, 0x132a180, 0xc00017e300, 0xc00005fac0, 0xc000188548, 0xc00017e300, 0xc0001ada48)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/internal/helper/plugin/grpc_provider.go:206 +0x1df
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ValidateResourceTypeConfig_Handler(0x1079a00, 0xc000188548, 0x132a180, 0xc00017e300, 0xc00008c600, 0x0, 0x132a180, 0xc00017e300, 0xc000000a00, 0xf9)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/internal/tfplugin5/tfplugin5.pb.go:3081 +0x21e
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00012c000, 0x1337940, 0xc0003b4180, 0xc000172600, 0xc0003b95f0, 0x1a68590, 0x0, 0x0, 0x0)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x467
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: google.golang.org/grpc.(*Server).handleStream(0xc00012c000, 0x1337940, 0xc0003b4180, 0xc000172600, 0x0)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd44
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004de260, 0xc00012c000, 0x1337940, 0xc0003b4180, 0xc000172600)
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xa8
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-04-18T14:32:17.606+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1:      C:/Users/mazia/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa8
2020/04/18 14:32:17 [WARN] <root>: eval: *terraform.EvalValidateResource, non-fatal err: rpc error: code = Unavailable desc = transport is closing
2020/04/18 14:32:17 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/04/18 14:32:17 [TRACE] [walkValidate] Exiting eval tree: azuredevops_build_definition.default
```

### Expected Behavior

Resource created.

### Actual Behavior

Terraform crash.

### Steps to Reproduce

- `terraform plan`

### Important Factoids

Resource works properly when the path is null or "\\\\"

**Comment by nmiodice** [comment]
Fix implemented here - https://github.com/microsoft/terraform-provider-azuredevops/pull/288

**Comment by nmiodice** [comment]
Fixed in the referenced PR
