### ISSUE TITLE
Error: The terraform-provider-azuredevops_v0.1.7 plugin crashed!

### ISSUE THREAD

**Issue by huats** [microsoft/terraform-provider-azuredevops#460]
Using Terraform 1.0.5 I am facing that error during terraform plan.

Please note that this code was running without issue 1 month ago.
```log
╷
│ Error: Plugin did not respond
│ 
│   with azuredevops_serviceendpoint_aws.aws_service_endpoint,
│   on azure-devops.tf line 8, in resource "azuredevops_serviceendpoint_aws" "aws_service_endpoint":
│    8: resource "azuredevops_serviceendpoint_aws" "aws_service_endpoint" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with azuredevops_variable_group.variable_group,
│   on azure-devops.tf line 17, in resource "azuredevops_variable_group" "variable_group":
│   17: resource "azuredevops_variable_group" "variable_group" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-azuredevops_v0.1.7 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf23ba0]

goroutine 99 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.doBaseFlattening(0xc000546e70, 0xc00077e400, 0xc0002c6210)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:112 +0x1a0
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.flattenServiceEndpointAws(0xc000546e70, 0xc00077e400, 0xc0002c6210)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_aws.go:81 +0x45
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointReadFunc.func1(0xc000546e70, 0xfd5000, 0xc000266500, 0xc000546e70, 0x0)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:207 +0x278
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000311680, 0xc0001bcd20, 0xfd5000, 0xc000266500, 0xc00011e638, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00011e420, 0x13c8890, 0xc00078a480, 0xc000114b40, 0xc00011e420, 0xc00078a480, 0xc000609ba0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1182fe0, 0xc00011e420, 0x13c8890, 0xc00078a480, 0xc000114ae0, 0x0, 0x13c8890, 0xc00078a480, 0xc0001b3b80, 0x25a)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000138380, 0x13d6578, 0xc000102f00, 0xc0003fe100, 0xc000283980, 0x19b92d0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000138380, 0x13d6578, 0xc000102f00, 0xc0003fe100, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001641c0, 0xc000138380, 0x13d6578, 0xc000102f00, 0xc0003fe100)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-azuredevops_v0.1.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by xuzhang3** [comment]
@huats Can you share your TF script?

**Comment by huats** [comment]
Sure @xuzhang3 

---
```hcl
resource "azuredevops_serviceendpoint_aws" "aws_service_endpoint" {
  project_id            = var.azure_devops.project_id
  service_endpoint_name = var.azure_devops.aws_service_endpoint.service_endpoint_name
  description           = var.azure_devops.aws_service_endpoint.description
  access_key_id         = module.iam.terraform_user_access_key_id
  secret_access_key     = module.iam.terraform_user_secret_access_key
}


resource "azuredevops_variable_group" "variable_group" {
  project_id   = var.azure_devops.project_id
  name         = var.azure_devops.variable_group.name
  description  = var.azure_devops.variable_group.description
  allow_access = var.azure_devops.variable_group.allow_access

  dynamic "variable" {
    for_each = local.azure_devops.variable_group.variables

    content {
      name  = variable.value.name
      value = variable.value.value
    }
  }

  dynamic "variable" {
    for_each = local.azure_devops.variable_group.secrets

    content {
      name         = variable.value.name
      secret_value = variable.value.value
      is_secret    = true
    }
  }
}
```

Of course I have some variables that are defined next to it.

---

**Comment by xuzhang3** [comment]
@huats I cannot reproduce this error, can you help get the service connection from with this API (https://dev.azure.com/{organization}/{project}/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4)

**Comment by huats** [comment]
> @huats I cannot reproduce this error, can you help get the service connection from with this API ([https://dev.azure.com/{organization}/{project}/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4](https://dev.azure.com/%7Borganization%7D/%7Bproject%7D/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4))

I am sorry but I don't understand what you are asking me about the service connection...

**Comment by xuzhang3** [comment]
@hauts `azuredevops_serviceendpoint_aws` is of the service connection, if you have created this resource by terraform, you can find  it in `project -> Project Settings -> Service Connections`. The root issue here seems the service response does not have the `Authorization.Scheme` while my test resource always have this values, so can you help use the API (https://dev.azure.com/{organization}/{project}/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4) to  check if service response have `Authorization.Scheme`

Response example:
```json
{
      "data": {
        
      },
      "id": "xxxx",
      "name": "aws",
      "type": "aws",
      "url": "https://aws.amazon.com/",
      "createdBy": {
        "displayName": "test user",
        "url": "https://spsprodsea1.vssps.visualstudio.com/xxxx/_apis/Identities/xxxx",
        "_links": {
          "avatar": {
            "href": "https://dev.azure.com/xxxx/_apis/GraphProfile/MemberAvatars/xxxx"
          }
        },
        "id": "xxxx",
        "uniqueName": "",
        "imageUrl": "",
        "descriptor": "xxxxx"
      },
      "description": "Managed by AzureDevOps",
      "authorization": {
        "parameters": {
          "assumeRoleArn": "",
          "externalId": "",
          "roleSessionName": "",
          "username": "00000000-0000-0000-0000-000000000000"
        },
        "scheme": "UsernamePassword"
      },
      "isShared": false,
      "isReady": true,
      "owner": "Library",
      "serviceEndpointProjectReferences": [
        {
          "projectReference": {
            "id": "00000000-0000-0000-0000-000000000000",
            "name": "ADOTest"
          },
          "name": "aws",
          "description": "Managed by AzureDevOps"
        }
      ]
    }
```

**Comment by huats** [comment]
@xuzhang3 
Thanks for the explanation.

WHen I visit that URL I simply get 

`{"count":0,"value":[]}`

But apparently some others from my team are getting different answer with many stuffs. I'll try to figure out if I find the Authorization.Scheme you are mentionning.

**Comment by huats** [comment]
@xuzhang3 you nailed it. Once I have been granted administrator I have been able to use TF correctly. May be there is something to catch to better handle permission. But I won't be able to help since I have coded in Go :( thanks a lot ! I let you close it.

**Comment by xuzhang3** [comment]
closing this issue, feel free to open another issue if you  have questions

**Comment by vital-dhaveloose** [comment]
Just FYI: I have also experienced this issue and would humbly advise to improve the error message.

**Comment by xuzhang3** [comment]
@vital-dhaveloose  Thanks for your feedback. Currently, the error message and exceptions are simply returned to users and the context information is not handled carefully. I have add this issue to our backlog, the exceptions  and error messages should be handled properly.
