### ISSUE TITLE
Plugin did not respond. The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call.

### ISSUE THREAD

**Issue by MattNewbill** [microsoft/terraform-provider-azuredevops#469]
Encountering error when trying to run terraform plan. This was working a couple months ago.

```
Error: Plugin did not respond
│
│   with module.devops.azuredevops_group.adbookpsp,
│   on ..\modules\ci\main.tf line 22, in resource "azuredevops_group" "adbookpsp":
│   22: resource "azuredevops_group" "adbookpsp" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.devops.azuredevops_serviceendpoint_azurecr.azurecr,
│   on ..\modules\ci\main.tf line 28, in resource "azuredevops_serviceendpoint_azurecr" "azurecr":
│   28: resource "azuredevops_serviceendpoint_azurecr" "azurecr" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azuredevops_v0.1.7 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x12d5985]

goroutine 69 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.doBaseFlattening(0xc0004a69a0, 0xc000308a00, 0xc0005b56e0)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:112 +0x1a5
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.flattenServiceEndpointAzureCR(0xc0004a69a0, 0xc000308a00, 0xc0005b56e0)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go:97 +0x4a
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointReadFunc.func1(0xc0004a69a0, 0x1387500, 0xc000482100, 0xc0004a69a0, 0x0)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:207 +0x278
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00021a6e0, 0xc0002f4e60, 0x1387500, 0xc000482100, 0xc000696580, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00008e980, 0x177f090, 0xc0003657d0, 0xc000480c60, 0xc00008e980, 0xc0003657d0, 0xc0004b9ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1535c40, 0xc00008e980, 0x177f090, 0xc0003657d0, 0xc000480c00, 0x0, 0x177f090, 0xc0003657d0, 0xc0004d8500, 0x265)       
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003bf6c0, 0x178d618, 0xc000296780, 0xc000662000, 0xc00025da40, 0x1d7a1f0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003bf6c0, 0x178d618, 0xc000296780, 0xc000662000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028c710, 0xc0003bf6c0, 0x178d618, 0xc000296780, 0xc000662000)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-azuredevops_v0.1.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I believe this may be related to [this ](https://github.com/microsoft/terraform-provider-azuredevops/issues/460) ticket.

**Comment by xuzhang3** [comment]
@MattNewbill  Are you trying to create some kind service connection?   This issue looks like same to #460

**Comment by MattNewbill** [comment]
@xuzhang3  Sorry for the slow response. Your note helped me identify the issue.

We were trying to create a service connection that already existed. For whatever reason we were getting this error when trying to run terraform plan/apply. We were able to fix the issue by manually deleting the service connection and then run terraform apply again(to recreate the service connection). 

Hope this helps someone in the future.

Best
Matt
