### ISSUE TITLE
Plugin crashed while adding features to existing projects

### ISSUE THREAD

**Issue by rob-zz** [microsoft/terraform-provider-azuredevops#593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1

### Affected Resource(s)

* `azuredevops_project`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

```
Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

╷
│ Error: Plugin did not respond
│ 
│   with azuredevops_project.projects["test2robbert"],
│   on devops_projects.tf line 2, in resource "azuredevops_project" "projects":
│    2: resource "azuredevops_project" "projects" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with azuredevops_project.projects["testrobbert"],
│   on devops_projects.tf line 2, in resource "azuredevops_project" "projects":
│    2: resource "azuredevops_project" "projects" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azuredevops_v0.2.1 plugin:

fatal error: concurrent map writes

goroutine 84 [running]:
runtime.throw(0x1047acb34, 0x15)
	runtime/panic.go:1117 +0x54 fp=0x14000720b90 sp=0x14000720b60 pc=0x10404dff4
runtime.mapassign_faststr(0x10499e6a0, 0x14000383290, 0x1047a1ec9, 0x9, 0x104937920)
	runtime/map_faststr.go:291 +0x3a8 fp=0x14000720c00 sp=0x14000720b90 pc=0x10402e1b8
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/core.getProjectFeatureNameMapReverse(0x1400026a150)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/core/resource_project_features.go:116 +0xd0 fp=0x14000720cb0 sp=0x14000720c00 pc=0x104721ea0
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/core.getProjectFeatureID(...)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/core/resource_project_features.go:123
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/core.validateProjectFeatures(0x1049a33e0, 0x140006e4cc0, 0x1047a11ca, 0x8, 0x104980520, 0x0, 0x14000720e00, 0x10407b400, 0x14000720e68, 0x10429aa30)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/core/resource_project_features.go:87 +0x118 fp=0x14000720dd0 sp=0x14000720cb0 pc=0x1047217d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Schema).validateFunc(0x140004a4280, 0x1049a33e0, 0x140006e4cc0, 0x1047a11ca, 0x8, 0x140004931f0, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:441 +0x60 fp=0x14000720f50 sp=0x14000720dd0 pc=0x10431f230
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateMap(0x14000383f50, 0x1047a11ca, 0x8, 0x1049a33e0, 0x140006e4cc0, 0x140004a4280, 0x140006e4c60, 0x140004931f0, 0x1, 0x1, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1824 +0x874 fp=0x140007211c0 sp=0x14000720f50 pc=0x104327e04
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateType(0x14000383f50, 0x1047a11ca, 0x8, 0x1049a33e0, 0x140006e4cc0, 0x140004a4280, 0x140006e4c60, 0x140004931f0, 0x1, 0x1, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:2111 +0x374 fp=0x140007212c0 sp=0x140007211c0 pc=0x10432a304
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validate(0x14000383f50, 0x1047a11ca, 0x8, 0x140004a4280, 0x140006e4c60, 0x140004931f0, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1534 +0x5e0 fp=0x140007215b0 sp=0x140007212c0 pc=0x104325350
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateObject(0x14000383f50, 0x0, 0x0, 0x14000383f50, 0x140006e4c60, 0x10500e748, 0x0, 0x0, 0x0, 0x104afcbf8, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:1970 +0x20c fp=0x14000721870 sp=0x140007215b0 pc=0x104328e2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Validate(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/schema.go:649
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Validate(0x14000445dc0, 0x140006e4c60, 0x1400003a0c0, 0x13, 0x140004ce568)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:542 +0x4c fp=0x14000721940 sp=0x14000721870 pc=0x10431564c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ValidateResource(0x14000380f00, 0x1400003a0c0, 0x13, 0x140006e4c60, 0x140006e4840, 0x140006e4c60, 0x14000698018)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:254 +0x130 fp=0x140007219b0 sp=0x14000721940 pc=0x104312970
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ValidateResourceTypeConfig(0x140003844b0, 0x104b05d78, 0x14000478200, 0x14000124f00, 0x1047a94c1, 0x12, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:230 +0x19c fp=0x14000721a30 sp=0x140007219b0 pc=0x104308d3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ValidateResourceTypeConfig(0x140000a6100, 0x104b05e20, 0x14000478200, 0x14000478000, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:503 +0x22c fp=0x14000721b20 sp=0x14000721a30 pc=0x1045fc8fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ValidateResourceTypeConfig_Handler(0x104a95900, 0x140000a6100, 0x104b05e20, 0x140006e4300, 0x14000346240, 0x0, 0x104b05e20, 0x140006e4300, 0x14000648280, 0x12a)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:272 +0x1c8 fp=0x14000721b90 sp=0x14000721b20 pc=0x1045ebaa8
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002a2c40, 0x104b12cb8, 0x14000001c80, 0x140003f2a00, 0x140000a45a0, 0x104fd1a30, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8 fp=0x14000721e40 sp=0x14000721b90 pc=0x1045a13f8
google.golang.org/grpc.(*Server).handleStream(0x140002a2c40, 0x104b12cb8, 0x14000001c80, 0x140003f2a00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50 fp=0x14000721f60 sp=0x14000721e40 pc=0x1045a4aa0
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000038220, 0x140002a2c40, 0x104b12cb8, 0x14000001c80, 0x140003f2a00)
	google.golang.org/grpc@v1.32.0/server.go:859 +0x94 fp=0x14000721fb0 sp=0x14000721f60 pc=0x1045b0b24
runtime.goexit()
	runtime/asm_arm64.s:1130 +0x4 fp=0x14000721fb0 sp=0x14000721fb0 pc=0x1040816c4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0x1400034be68)
	github.com/hashicorp/go-plugin@v1.4.1/server.go:469 +0x710
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0x14000380e40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/plugin/serve.go:147 +0xb0
main.main()
	github.com/microsoft/terraform-provider-azuredevops/main.go:10 +0x44

goroutine 9 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x140000a4270, 0xe, 0x0, 0x0)
	github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:121 +0x6c
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0x14000108af0)
	github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:411 +0x70
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	github.com/hashicorp/go-plugin@v1.4.1/grpc_server.go:85 +0x310

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x12c394da0, 0x72, 0x104add380)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x1400007a138, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x1400007a120, 0x140001fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x180
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0x14000388028, 0x140001fb000, 0x1000, 0x1000, 0x400, 0x10495c2e0, 0xff6134464a77bf01)
	os/file.go:117 +0x60
bufio.(*Reader).Read(0x140000f5750, 0x1400043c800, 0x400, 0x400, 0x0, 0x0, 0x0)
	bufio/bufio.go:227 +0x20c
github.com/hashicorp/go-plugin.copyChan(0x104b17008, 0x140003ba600, 0x1400010a540, 0x104af0348, 0x14000388028)
	github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:181 +0x90
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:37 +0x94

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x12c394bd0, 0x72, 0x104add380)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x1400007a1f8, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x1400007a1e0, 0x140001f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x180
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0x14000388038, 0x140001f3000, 0x1000, 0x1000, 0x400, 0x10495c2e0, 0xd82cfe3fb9689701)
	os/file.go:117 +0x60
bufio.(*Reader).Read(0x140000f5f50, 0x14000150400, 0x400, 0x400, 0x0, 0x7d6e81e5eb9e72f9, 0x655517cc2d54d57f)
	bufio/bufio.go:227 +0x20c
github.com/hashicorp/go-plugin.copyChan(0x104b17008, 0x140003ba600, 0x1400010a5a0, 0x104af0348, 0x14000388038)
	github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:181 +0x90
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:38 +0xd4

Error: The terraform-provider-azuredevops_v0.2.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Added features to existing projects.

### Actual Behavior

'terraform apply' crashed with above stack trace.

### Steps to Reproduce

Unsure, can't reproduce for now.

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
dup #595. concurrent bug.
