### ISSUE TITLE
Error: Plugin did not respond on resource 'azuredevops_serviceendpoint_github'

### ISSUE THREAD

**Issue by azmukhtar** [microsoft/terraform-provider-azuredevops#620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_serviceendpoint_github`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.1.0"
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">= 0.2.0"
    }
  }
}

resource "azuredevops_serviceendpoint_github" "github" {
  project_id            = var.project_id
  service_endpoint_name = "GitHub Service Connection"

  auth_personal {
    personal_access_token = var.github_org_token
  }
}
```

### Debug Output
https://gist.github.com/azmukhtar/5366f723aead4724590374f0d705741a

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@azmukhtar I cannot reproduce, which permission you granted to your PAT?  This error happened when the project the service connection bind to is null.

**Comment by mazlumtoprak** [comment]
I can reproduce it with the following settings and I gave my PAT full access for debugging purpose
```
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "~> 1.24.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.15.0"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "~> 0.2.2"
    }
  }
```
### Stacktrace
```
Stack trace from the terraform-provider-azuredevops_v0.2.2 plugin:

panic: interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}

goroutine 29 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.expandServiceEndpointKubernetes(0x0?)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go:213 +0x13a6
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointUpdateFunc.func1(0x0?, {0xc7eba0?, 0xc0002daea0})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:242 +0x53
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xf64d80?, {0xf64d80?, 0xc0004262a0?}, 0xd?, {0xc7eba0?, 0xc0002daea0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/resource.go:364 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00045dc00, {0xf64d80, 0xc0004262a0}, 0xc000359520, 0xc000291f00, {0xc7eba0, 0xc0002daea0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/resource.go:482 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000293638, {0xf64cd8?, 0xc0002304c0?}, 0xc000299040)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003f4460, {0xf64d80?, 0xc0002399e0?}, 0xc00021f180)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdd7060?, 0xc0003f4460}, {0xf64d80, 0xc0002399e0}, 0xc0006d2ba0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002aaa80, {0xf67800, 0xc00049eb60}, 0xc000413200, 0xc000494450, 0x1473ea0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002aaa80, {0xf67800, 0xc00049eb60}, 0xc000413200, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-azuredevops_v0.2.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```


When pinpointing azuredevops provider to version **0.2.1**, I can apply my changes. Running on terraform 1.2.4.

**Comment by xuzhang3** [comment]
@mazlumtoprak originally error is the project which this connection bind to is not returned, your error is `yaml`  parse error , can you help check the `context` block?

**Comment by xuzhang3** [comment]
This appears to be a permissions issue causing the service connection to not return completely. #1193 is attempting to fix this.
