### ISSUE TITLE
Plugin crash for azuredevops_variable_group in Azure China Cloud

### ISSUE THREAD

**Issue by markbangert** [microsoft/terraform-provider-azuredevops#674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform version 1.1.5
Azure DevOps Provider version 0.3.0

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

We have a standard variable group definition. Everything worked fine until 24 November where we had the last run.

### Panic Output

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc26239]

goroutine 83 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.flattenVariables(0xc0000fb300?, 0xc0003d6360)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:446 +0x39
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.flattenVariableGroup(0xc00046e280?, 0xc0003d6360, 0xc00004a2d0?)
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:413 +0x12e
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.resourceVariableGroupRead(0x0?, {0xc9dbe0?, 0xc00023b440})
	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:225 +0x158
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xf8c420?, {0xf8c420?, 0xc0006c4ed0?}, 0xd?, {0xc9dbe0?, 0xc00023b440?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000376b60, {0xf8c420, 0xc0006c4ed0}, 0xc0003c7040, {0xc9dbe0, 0xc00023b440})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00035e8b8, {0xf8c420?, 0xc0006c4db0?}, 0xc0006b94c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00032af00, {0xf8c420?, 0xc0006c45d0?}, 0xc0000a4c00)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xdf8be0?, 0xc00032af00}, {0xf8c420, 0xc0006c45d0}, 0xc000235ce0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0xf8f040, 0xc0003c89c0}, 0xc0006c10e0, 0xc0003b4660, 0x14ad470, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0xf8f040, 0xc0003c89c0}, 0xc0006c10e0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-azuredevops_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Terraform plan completes succesfully

### Actual Behavior

During terraform plan the state refresh fails. However, this only happens in the Azure China Cloud, in the Azure Public cloud, where we also maintain a similar setup, everything is running smooth.

**Comment by xuzhang3** [comment]
Variable groups requires at least one variable per group, but this error message show there is not variable found in the group.  This seems to be the permission issue and only part of the group was returned.
