### ISSUE TITLE
Create AKS service connection with kubeconfig

### ISSUE THREAD

**Issue by michelefa1988** [microsoft/terraform-provider-azuredevops#687]
Due to [Issue](https://github.com/microsoft/terraform-provider-azuredevops/issues/670) and [issue](https://developercommunity.visualstudio.com/t/New-Kubernetes-service-connection-causes/10138123), I have started to migrate `azuredevops_serviceendpoint_kubernetes` configuration from `azure_subscription` to `kubeconfig`

I have tried something like below and I am unable to get it working. My goal is that that the AzureDevops AKS service connections are automatically created using ONLY terraform

My requests are:
1) Please update the documentation with a clear example (ensuring we can get the kube_config from the output of the azurerm_kubernetes_cluster resource
2) Documentation on kube_configs OUTPUTs is unclear. Are kube_config outputs base64 encoded or not? [kube_admin_config_raw](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_cluster#kube_admin_config_raw) describe the output as base64 encoded but not in the [azurerm_kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) module

~~3) When I try the example below, I get the following error, not sure if I am doing something wrong or its actually a bug~~

*Configuration*
```
data "azurerm_kubernetes_cluster" "aks-read" {
  name                = var.name
  resource_group_name = var.resource_group
}

resource "azuredevops_serviceendpoint_kubernetes" "serviceendpoint_kubernetes" {
  project_id            = data.azuredevops_project.p.id
  service_endpoint_name = var.service_endpoint_name
  apiserver_url         = var.apiserver_url
  authorization_type    = "AzureSubscription"

  kubeconfig {
    kube_config = data.azurerm_kubernetes_cluster.aks-read.kube_config_raw)
  }
```

*Error*
```
Stack trace from the terraform-provider-azuredevops_v0.3.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 31 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.expandServiceEndpointKubernetes(0x0?)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go:186 +0x128f
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointCreateFunc.func1(0x0?, {0x189cc00?, 0xc0004b86c0})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:167 +0x73
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1b8bda0?, {0x1b8bda0?, 0xc00026fef0?}, 0xd?, {0x189cc00?, 0xc0004b86c0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003f1ce0, {0x1b8bda0, 0xc00026fef0}, 0xc0004b1790, 0xc000489a80, {0x189cc00, 0xc0004b86c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000d3620, {0x1b8bda0?, 0xc00026fdd0?}, 0xc00026a960)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000282960, {0x1b8bda0?, 0xc00026ed50?}, 0xc0003b8310)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x19f8c40?, 0xc000282960}, {0x1b8bda0, 0xc00026ed50}, 0xc0003b82a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003dc000, {0x1b8ea40, 0xc000190b60}, 0xc0002f4900, 0xc000424750, 0x20b0620, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0003dc000, {0x1b8ea40, 0xc000190b60}, 0xc0002f4900, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-azuredevops_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by michelefa1988** [comment]
After alot of trial and error, the following code fixed my (3). Nevertheless I do suggest you add an example to your docs and ensure the OUTPUTs of AKS and AKS datasource are correct and up to date
```
resource "azuredevops_serviceendpoint_kubernetes" "serviceendpoint_kubernetes" {
  project_id            = data.azuredevops_project.p.id
  service_endpoint_name = "${var.name}-1"
  apiserver_url         = azurerm_kubernetes_cluster.aks.kube_config[0].host
  authorization_type    = "Kubeconfig"

  kubeconfig {
    kube_config = azurerm_kubernetes_cluster.aks.kube_config_raw
  }
}
```
