### ISSUE TITLE
azurerm_signalr_service_custom_certificate key vault in different subscription

### ISSUE THREAD

**Issue by sergiomcalzada** [microsoft/terraform-provider-azuredevops#872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform version: 1.4.6
provider registry.terraform.io/hashicorp/azurerm v3.71.0

### Affected Resource(s)

* `azurerm_signalr_service_custom_certificate`

### Panic Output

```
Stack trace from the terraform-provider-azurerm_v3.71.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b12235]

goroutine 106 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr.CustomCertSignalrServiceResource.Read.func1({0x7a4e028, 0xc004f31f20}, {0xc0015ce480, {0x7a4e8b0, 0xc0005a8b70}, 0xc004f19880, 0x0, {0x7a4fa30, 0xc424de8}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr/signalr_service_custom_certificate_resource.go:171 +0x415
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x7a4e028, 0xc004f31f20}, 0x7a4e060?, {0x64a9480?, 0xc0015ce480?})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:62 +0x1e5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x7a4e028, 0xc004f31f20}, 0x0?, {0x64a9480, 0xc0015ce480})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:188 +0xb8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00071c2a0, {0x7a4e060, 0xc004f31320}, 0xd?, {0x64a9480, 0xc0015ce480})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00071c2a0, {0x7a4e060, 0xc004f31320}, 0xc004f1d380, 0xc004f19700, {0x64a9480, 0xc0015ce480})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0009979f8, {0x7a4e060?, 0xc004f31200?}, 0xc000873130)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001a6280, {0x7a4e060?, 0xc004f30810?}, 0xc000929180)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x6e900a0?, 0xc0001a6280}, {0x7a4e060, 0xc004f30810}, 0xc000929110, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00024a1e0, {0x7a5e640, 0xc001970820}, 0xc004f2d560, 0xc0018e1e30, 0xc3e3d80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc00024a1e0, {0x7a5e640, 0xc001970820}, 0xc004f2d560, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.71.0_x5 plugin crashed!
```
### Expected Behavior

Custom certificate is added to the signalr service in azure and the command don't fails

### Actual Behavior

The custom certificate is added to the signalr service in azure but terraform crash with a panic

### Steps to Reproduce

Use a certificate that is hosted in a KeyVault that is not located in the same subscription

**Comment by sergiomcalzada** [comment]
wrong repo
