### ISSUE TITLE
provider azuredevops crashed at terraform plan

### ISSUE THREAD

**Issue by Brownie9** [microsoft/terraform-provider-azuredevops#912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```sh
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.44.0
+ provider registry.terraform.io/hashicorp/azurerm v3.77.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/microsoft/azuredevops v0.10.0
```

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurecr`
* `azuredevops_serviceendpoint_kubernetes`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_azurecr" "terra_acr_service_endpoint" {
  project_id                = data.azuredevops_project.devops_caribou_projet.id
  service_endpoint_name     = azurerm_container_registry.terra_acr.name
  resource_group            = azurerm_resource_group.terra_rgo.name
  azurecr_spn_tenantid      = data.azurerm_client_config.current.tenant_id
  azurecr_name              = azurerm_container_registry.terra_acr.name
  azurecr_subscription_id   = data.azurerm_client_config.current.subscription_id
  azurecr_subscription_name = "${local.environnement}"
}

resource "azuredevops_serviceendpoint_kubernetes" "terra_aks_service_endpoint" {
  project_id            = data.azuredevops_project.devops_caribou_projet.id
  service_endpoint_name = "aks01${local.environnement}"
  apiserver_url         = "https://${azurerm_kubernetes_cluster.terra_aks.fqdn}"
  authorization_type    = "AzureSubscription"

  azure_subscription {
    subscription_id     = data.azurerm_client_config.current.subscription_id
    subscription_name   = "${local.environnement}"
    tenant_id           = data.azurerm_client_config.current.tenant_id
    resourcegroup_id    = azurerm_resource_group.terra_rgo.name
    cluster_name        = azurerm_kubernetes_cluster.terra_aks.name
  }
}
```

### Panic Output

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc20ff2]

goroutine 30 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.resourceServiceEndpointAzureCRRead(0x0?, {0xcd0440?, 0xc0003d34a0})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go:127 +0xb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xfcbbc0?, {0xfcbbc0?, 0xc000462c30?}, 0xd?, {0xcd0440?, 0xc0003d34a0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000363260, {0xfcbbc0, 0xc000462c30}, 0xc0004d1e10, {0xcd0440, 0xc0003d34a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00018a5b8, {0xfcbbc0?, 0xc000462b10?}, 0xc00020f700)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002e6fa0, {0xfcbbc0?, 0xc000462180?}, 0xc00007f740)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xe313e0?, 0xc0002e6fa0}, {0xfcbbc0, 0xc000462180}, 0xc000254230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0xfce8c0, 0xc000214d00}, 0xc0001aad80, 0xc000375b90, 0x15078f0, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0xfce8c0, 0xc000214d00}, 0xc0001aad80, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-azuredevops_v0.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

A service endpoint for Kubernetes need to be created on my Azure DevOps project. The same for an Azure Container Registry.

### Actual Behavior

The plugin azure devops crashed at 'terraform plan'

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

I had the same problem with the version 0.9.1 of the plugin azure_devops.
I have the same problem (plugin crashed) if I comment this 2 ressources on my code.

### References

* #0000

**Comment by Brownie9** [comment]
I finally found the problem.
It was because the endpoint for ACR connection on Azure DevOps was deleted then recreated.

So the new id was not the same as the id found on the tfstate file.
I just delete the resource on my tfstate file and import the new resource.

```hcl
terraform state list
terraform state rm azuredevops_serviceendpoint_azurecr.terra_acr_service_endpoint
terraform import -var "KV_ARM_OBJECT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -var-file="./environnements/terra_int01.tfvars" azuredevops_serviceendpoint_azurecr.terra_acr_service_endpoint xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
