### ISSUE TITLE
Provider Crash with azuredevops_group_entitlement

### ISSUE THREAD

**Issue by DeepPatel318** [microsoft/terraform-provider-azuredevops#924]
Terraform Config:
Terraform Version : 1.6.3
Azure DevOps Plugin Version : 0.10.0

Terraform Plan output:
2023-11-09T20:08:05.4067709Z [1mPlan:[0m 13 to add, 0 to change, 0 to destroy.
2023-11-09T20:08:05.4068247Z [31m╷[0m[0m
2023-11-09T20:08:05.4068636Z [31m│[0m [0m[1m[31mError: [0m[0m[1mRequest cancelled[0m
2023-11-09T20:08:05.4069093Z [31m│[0m [0m
2023-11-09T20:08:05.4069422Z [31m│[0m [0m[0m  with data.azuredevops_groups.this,
2023-11-09T20:08:05.4070030Z [31m│[0m [0m  on data.tf line 13, in data "azuredevops_groups" "this":
2023-11-09T20:08:05.4070687Z [31m│[0m [0m  13: data "azuredevops_groups" "this" [4m{[0m[0m
2023-11-09T20:08:05.4071627Z [31m│[0m [0m
2023-11-09T20:08:05.4072097Z [31m│[0m [0mThe plugin.(*GRPCProvider).ValidateDataResourceConfig request was
2023-11-09T20:08:05.4072671Z [31m│[0m [0mcancelled.
2023-11-09T20:08:05.4072949Z [31m╵[0m[0m
2023-11-09T20:08:05.4073187Z [31m╷[0m[0m
2023-11-09T20:08:05.4073552Z [31m│[0m [0m[1m[31mError: [0m[0m[1mRequest cancelled[0m
2023-11-09T20:08:05.4074017Z [31m│[0m [0m
2023-11-09T20:08:05.4074729Z [31m│[0m [0m[0m  with module.azure_resource_group_deployment["rg-headcountplanq"].azuredevops_group_entitlement.this,
2023-11-09T20:08:05.4076194Z [31m│[0m [0m  on .terraform\modules\azure_resource_group_deployment\devops.tf line 24, in resource "azuredevops_group_entitlement" "this":
2023-11-09T20:08:05.4077342Z [31m│[0m [0m  24: resource "azuredevops_group_entitlement" "this" [4m{[0m[0m
2023-11-09T20:08:05.4077898Z [31m│[0m [0m
2023-11-09T20:08:05.4078399Z [31m│[0m [0mThe plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

**Comment by DeepPatel318** [comment]
I tried to run the terraform plan in other subscription and the issue didn't occurred, I think it has to do with rate limit to graph API that is denying access resources using API.

**Comment by EraYaN** [comment]
I get a very similar issue:

```
Stack trace from the terraform-provider-azuredevops_v1.0.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1407351]

goroutine 115 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/memberentitlementmanagement.importGroupEntitlement(0xc00030e380, {0x151ed60?, 0xc0004cb1e0})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/memberentitlementmanagement/resource_group_entitlement.go:263 +0x251
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc0000aaf60, {0x18605c0, 0xc00059c900}, 0xc00051d5d0, {0xc0008840f0, 0x24})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/provider.go:387 +0x1ce
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc0003f67e0, {0x18605c0?, 0xc00035e690?}, 0xc00030c060)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1088 +0xf4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc0003b9220, {0x18605c0?, 0xc000698000?}, 0xc00037a0a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:848 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0x169c9a0?, 0xc0003b9220}, {0x18605c0, 0xc000698000}, 0xc000422000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0x1863320, 0xc000467520}, 0xc000292360, 0xc000480360, 0x1df3238, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0x1863320, 0xc000467520}, 0xc000292360, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-azuredevops_v1.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```


```hcl
resource "azuredevops_group_entitlement" "group" {
  display_name = "Group Name"
}

import {
  id="<guid>"
  to=azuredevops_group_entitlement.group
}
```
